spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.18.200:3306/spring_boot_quartz?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      schema: classpath:schema/tables_mysql_innodb.sql
      initialize-schema: never
  thymeleaf:
    cache: false
