spring:
  datasource:
    url: jdbc:mysql://192.168.18.200:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(akl7gZDq1uxjDA4o6SUZ2A==)
    password: ENC(WgNJDGk/78FBy+RvNoMkLw==)
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    #deprecated 已经过时了
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL55Dialect
    properties:
      hibernate:
        format_sql: false
jasypt:
  encryptor:
    password: JH8AS90jasH