spring:
  datasource:
    url: jdbc:mysql://192.168.18.200:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(HA0WkJ5IeX5fv3u2gJ/yIQ==)
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    #deprecated 已经过时了
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL55Dialect
    properties:
      hibernate:
        format_sql: false
jasypt:
  encryptor:
    #    VJp9xCBuS/pGsYZCEHhDWA==
    password: JH8AS90jasH