spring:
  datasource:
    username: postgres
    password: pg
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.163.110:5432/spring-boot-security-jwt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false