server:
  port: 80
spring:
  application:
    name: spring-boot-v2
  mandatory-file-encoding: UTF-8
  datasource:
    url: jdbc:mysql://192.168.163.109:3306/spring_boot?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
