spring:
  application:
    name: spring-boot-multiple-database
  mandatory-file-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false
mysql:
  db:
    datasource:
      username: root
      password: root
      url: jdbc:mysql://192.168.163.110:3306/spring_boot?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
postgres:
  db:
    datasource:
      username: postgres
      password: pg
      url: jdbc:postgresql://192.168.163.110:5432/spring_boot
      driver-class-name: org.postgresql.Driver
oracle:
  db:
    datasource:
      url: jdbc:oracle:thin:@192.168.163.110:1521:orcl
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: orcl
      password: orcl
